### ISSUE TITLE
Ability to customize behaviour of non-integral scroll offset

### ISSUE THREAD

**Issue by kirkbyo** [Flutter-Bounty-Hunters/page_list_viewport#52]
When the user either flings or moves the viewport to a new position, the final origin of the viewport has a trailing decimal. This will result in the content to be positioned on half pixels and in turn result in further anti-aliasing. 

The native scroll view on iOS (`UIScrollView`) will only clamp the final scroll offsets of either .0 or 0.5. See the following sample app written in native Swift which displays a scrollable gradient and the scroll views text offset in the centre.

https://github.com/Flutter-Bounty-Hunters/page_list_viewport/assets/8084674/745df717-8890-4f6d-b6be-b03970cfaf06

<details>
<summary>Sample swift code</summary>

```swift
//
//  ViewController.swift
//  Gradient Scroller
//
//  Created by Ozzie Kirkby on 2023-08-10.
//

import UIKit

class ViewController: UIViewController, UIScrollViewDelegate {
    let gradientHeight: CGFloat = 4000
    var scrollView: UIScrollView!
    var gradientView: UIView!
    var offsetLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupScrollView()
        setupGradientView()
        setupOffsetLabel()
    }
    
    func setupScrollView() {
        scrollView = UIScrollView(frame: view.bounds)
        scrollView.delegate = self
        scrollView.contentSize = CGSize(width: view.bounds.width, height: gradientHeight)
        view.addSubview(scrollView)
    }
    
    func setupGradientView() {
        gradientView = UIView(frame: CGRect(x: 0, y: 0, width: view.bounds.width, height: gradientHeight))
        let gradientLayer = CAGradientLayer()
        gradientLayer.frame = gradientView.bounds
        gradientLayer.colors = [UIColor.white.cgColor, UIColor.red.withAlphaComponent(0.8).cgColor] // Add your desired colors
        gradientView.layer.addSublayer(gradientLayer)
        scrollView.addSubview(gradientView)
    }
    
    func setupOffsetLabel() {
        offsetLabel = UILabel(frame: CGRect(x: 0, y: 0, width: view.bounds.width, height: 30))
        offsetLabel.textAlignment = .center
        offsetLabel.textColor = .black
        offsetLabel.center = view.center
        view.addSubview(offsetLabel)
    }
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        let yOffset = scrollView.contentOffset.y
        offsetLabel.text = "Offset: \(yOffset)"
    }
}
```

</details>

## Proposal

Add a new API to the `PageListViewport` that allows the user to customize the scroll view clamping behavior.

```dart
enum PageListViewportScrollClamp {
   clampToZero,
   clampToZeroOrHalf,
   none
}
```

**Comment by matthew-carroll** [comment]
Do we really need this to be configurable? If you want it clamped, is there any reason that someone else would want it not clamped?

**Comment by kirkbyo** [comment]
@matthew-carroll I would think so, if you have a display that performs well with anti-aliasing (e.g. have a high DPI) you might prefer half-pixel rounding or no rounding at all. Compared to displays with a mid-range DPI and/or monochrome pixels should opt to `clampToZero` to avoid sub-pixel alignment problems.
