### ISSUE TITLE
Spring effect for scrolls with small translations

### ISSUE THREAD

**Issue by kirkbyo** [Flutter-Bounty-Hunters/page_list_viewport#6]
After https://github.com/Flutter-Bounty-Hunters/page_list_viewport/pull/2, it seems like with some scrolls with a small enough translation, the viewport seems to spring.

Demo (video size was greater than Github's 10mb limit): https://www.loom.com/share/42995ab3f996441089d9ce1d4590f46e

**Rough reproduction**
I haven't figured how a consistent reproduction for this yet, but it seems to occur the most when:
1. scale the viewport to ~150%
2. Pan with the intention of only ~100-200 pixels and immediately release.
3. Notice how the viewport seems to spring into its final position.

**Comment by kirkbyo** [comment]
@matthew-carroll

**Comment by matthew-carroll** [comment]
I can't seem to reproduce this

**Comment by matthew-carroll** [comment]
Copying my chat message here for general visibility:

> For the panning velocity at the end of a gesture, I think we need to decide what we expect to happen there.
> 
> I tried adding an average velocity, to overpower the final reverse motion. But now that creates a new issue. If you do slightly reverse motion at the end, and then release, the content continues in the original direction. It's kind of like the inverse of the current problem.
> 
> When thinking about regular scrolling, we might check the sign on the direction of motion to detect when direction reversed, and when it does, kill the previous velocity. However, we're not implementing scrolling. We're implementing panning. So direction isn't as simple as a positive or negative sign, it's a vector. Instead of reversing direction, the user might turn to the left, or to the right, and might do so a little, or a lot.
> 
> What you're experiencing right now with that spring effect is technically correct. The content moves in the direction that you end your motion. But since that's not the effect you want, we need to figure out what you do want.
>

**Comment by kirkbyo** [comment]
@matthew-carroll have you been able to reproduce and confirm the theory around the end drag velocity vector having a different direction than the vector 
I have been playing around with a couple different readers. Xodo seems to be behave similarly to ours except they limit overall "springiness".

Apple PDF's does not have any springiness. They seem to just clamp it to prevent the spring.

I am not sure I follow this point:

> So direction isn't as simple as a positive or negative sign, it's a vector. Instead of reversing direction, the user might turn to the left, or to the right, and might do so a little, or a lot.

Could we not enforce that the end-drag velocity must have the same direction as the last drag update velocity? for example, some rough pseudo code:

```dart
Offset? _dragUpdateVelocity;

void _onDragUpdate(details) {
   _dragUpdateVelocity = details.pixelsPerSecond;
}

void _onDragEnd(details) {
   final lastVelocity = Offset.fromDirection(_dragUpdateVelocity!.direction, details.pixelsPerSecond)
}
```

This way the vector will have same direction but the magnitude will vary according to the end velocity.

**Comment by matthew-carroll** [comment]
> Could we not enforce that the end-drag velocity must have the same direction as the last drag update velocity? for example, some rough pseudo code

It sounds like you're assuming that the finger lift only ever takes one frame. But that's probably not the case. 

At a high level, the problem you're seeing is that humans tend to lift their finger by pulling back instead of pulling up. For some that will happen faster or slower. Some will drag more or less. Some will move in a nearly direct backward motion, while others will sway left or right on the way back.

The question is, how would you like to smooth out that unintended human behavior?

**Comment by kirkbyo** [comment]
Spent some time tuning this further. I have found that a `FrictionSimulation` wrapped in a `ClampedSimulation` with tuned parameters seems to exhibit our desired scroll de-acceleration without the springiness described in this issue.

## Summary of changes
**Clamped Friction Simulation**
```dart
class PanningFrictionSimulation {
  static const kVerticalDrag = 0.095;
  static const kHorizontalDrag = 0.0425;

  PanningFrictionSimulation({
    required Offset position,
    required Offset velocity,
  })  : _position = position,
        _velocity = velocity {
    _xSimulation = ClampedSimulation(
      FrictionSimulation(kHorizontalDrag, _position.dx, _velocity.dx),
      dxMin: -3000,
      dxMax: 3000,
    );
    _ySimulation = ClampedSimulation(
      FrictionSimulation(kVerticalDrag, _position.dy, _velocity.dy, constantDeceleration: 2.35),
      dxMin: -2000,
      dxMax: 3000,
    );
  }
```
https://github.com/kirkbyo/page_list_viewport/blob/c0c2811ed8e7549283571c3210545749e68b6282/lib/src/deprecated_gestures.dart#L402-L421
Clamping the velocity controls how long the simulation will run for, while the dampening factor controls how “slippery” the simulation feels (e.g. how quickly it accelerates). I found by testing other viewports that the horizontal and vertical components seemed to have different friction factors. The `constantDeceleration` affects how smoothly the viewport feels as it is approaching zero.

**Prevent momentum if the fling velocity is below threshold and translation is not greater than threshold**
```dart
    final translationDistance = (_lastFocalPosition - _startPosition).distance;
    if (translationDistance > kViewportMinFlingDistance &&
        details.velocity.pixelsPerSecond.distance < kViewportMinFlingVelocity) {
      // The user was readjusting the viewport by dragging it to the
      // new position.
      return;
    }
```
https://github.com/kirkbyo/page_list_viewport/blob/c0c2811ed8e7549283571c3210545749e68b6282/lib/src/deprecated_gestures.dart#L374-L380

Prevents the momentum from being applied when the user moves the viewport to a new position with their finger and their is trailing velocity as the finger is removed. The minimum distance threshold ensures that when the user is doing tiny pans, the momentum is still applied.

Constants I found work the best:

```
  static double kViewportMinFlingVelocity = 600;
  static double kViewportMinFlingDistance = 60;
```

This seems to work well for the reader where the user is primarily flinging and readjusting the viewport. We might want to make these parameters customizable for downstream consumers to allow for further tuning.
